spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    dev.marcosmoreira.consultorio: INFO

server:
  forward-headers-strategy: framework
